cart/urls.py
from django.urls import path
from .views import cart_detail, add_item, remove_item
from django.views.decorators.cache import cache_page


app_name = 'cart'


urlpatterns = [
    path('', cart_detail, name='cart-detail'),
    path('add/<int:artwork_id>/', add_item, name='cart-add'),
    path('remove/<int:artwork_id>/', remove_item, name='cart-remove'),
]

palette/urls.py
from django.urls import path
from .views import artwork_list, artwork_detail


app_name = 'palette'

urlpatterns = [
    path('', artwork_list, name='artwork-list'),
    path('<slug:genre_slug>/', artwork_list, name='artwork-list-genre'),
    path('<int:id>/<slug:slug>/', artwork_detail, name='artwork-detail'),
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    # path('__debug__/', include('debug_toolbar.urls')),
    path('', include('palette.urls', namespace='palette')),
]

# Settings for handling media.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

palette/models.py
from django.db.models import (Model, CharField, SlugField, DateTimeField,
                              Index, ImageField, PositiveIntegerField, URLField,
                              DecimalField, TextField, BooleanField, TextChoices,
                              ForeignKey, CASCADE)
from django.db.models.manager import Manager
from django.urls import reverse


# Custom manager for retrieving only available artworks.
class AvailableManager(Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_available=True)


class Genre(Model):
    name = CharField(max_length=250, unique=True)
    slug = SlugField(max_length=250)
    created = DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created']
        indexes = [
            Index(fields=['slug']),
            Index(fields=['name']),
        ]
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('palette:artwork-list-genre', args=[self.slug])
    
    
    
class Artwork(Model):
    class Edition(TextChoices):
        LIMITED = ('LT', 'limited')
        OPEN = ('OP', 'open')
        SINGULAR = ('SI', '1/1')
        
    name = CharField(max_length=250, unique=True)
    slug = SlugField(max_length=250)
    image = ImageField(upload_to='images/')
    description = TextField(max_length=255, blank=True)
    height = PositiveIntegerField(blank=True, null=True)
    width = PositiveIntegerField(blank=True, null=True)
    artist = CharField(max_length=250)
    instagram_link = URLField(max_length=255, blank=True)
    price = DecimalField(max_digits=9, decimal_places=2,
                         blank=True, null=True)
    quantity = PositiveIntegerField(default=1)
    edition = CharField(max_length=2, choices=Edition.choices, 
                     default=Edition.OPEN)
    is_available = BooleanField(default=True)
    genre = ForeignKey(Genre, related_name='artworks',
                       on_delete=CASCADE)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)
    
    objects = Manager()
    available = AvailableManager()
    
    class Meta:
        ordering = ['-created']
        indexes = [
            Index(fields=['id', 'slug']),
            Index(fields=['name']),
            Index(fields=['is_available']),
            Index(fields=['edition']),
        ]
        
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('palette:artwork-detail', args=[self.id, self.slug])
    

palette/views.py
from django.shortcuts import render
from .models import Genre, Artwork
from cart.forms import CartUpdateForm
from django.core.cache import cache


def artwork_list(request, genre_slug=None):
    ''' 
    If `genre_slug` is not provided, return all available artworks.
    Else return related genre and available artworks.
    Finally return `genre` to double as bool-check.
    '''
    genre = None
    genres = cache.get_or_set('all_genres', Genre.objects.all())
        
    artworks = cache.get_or_set('all_artworks', Artwork.available.all())
    
    if genre_slug:
        genre = Genre.objects.filter(slug=genre_slug).first()
        key = f'genre_{genre.id}_artworks'
        artworks = cache.get_or_set(key, Artwork.available.filter(genre=genre))
        
    return render(request, 'palette/list.html', {
        'genre': genre,
        'genres':genres,
        'artworks':artworks
    })
    

def artwork_detail(request, id, slug):
    key = f'artwork_{id}_{slug}'
    artwork = cache.get_or_set(key, Artwork.available.filter(id=id, slug=slug).first())
    if not artwork:
        return render(request, 'error/404.html',
                   {'error_message': 'An error occured during artwork retrieval',
                    'remove_subheader': True})
        
    form = CartUpdateForm()
    
    return render(request, 'palette/detail.html', {'artwork':artwork,
                                                   'form': form})

palette/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        {% block title %}Palette Portal{% endblock %}
    </title>

    <link href="{% static 'css/palette.css' %}" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/color-thief/2.3.2/color-thief.umd.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="{% static 'js/palette.js' %}"></script>
</head>

<body>
    <div class="header">
        <a href="/" id="header-hover">Palette Portal</a>
    </div>

    {% if not remove_subheader %}
        {% if not show_subheader %}
            <div class="ignore-subheader">
            </div>
        {% else %}
            <div class="subheader">
                <div class="cart">
                    {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                            {{ total_items }} item{{ total_items|pluralize }} found in <a href="{% url 'cart:cart-detail' %}">cart🛒</a>
                        {% else %}
                            <a href="{% url 'cart:cart-detail' %}">Cart🛒</a> is empty
                        {% endif %}
                    {% endwith %}
                </div>
            </div>
        {% endif %}

        <div class="content">
            {% block content %}{% endblock %}
        </div>
    {% else %}
        <div class="error">
            {% block error %}{% endblock %}
        </div>
    {% endif %}
</body>
</html>